### ISSUE TITLE
c_specific_example_2

### ISSUE THREAD

**Issue by rebeccajohnson88** [ilundberg/replication#5]
Commit [here](https://github.com/rebeccajohnson88/replication/blob/master/setting_the_target/code/c_specific_example_2.R)

1. _Coding of the maternal repartnering variable_

Two questions about the original code:

```
newpartner.yr3 = case_when(m3e2d %in% c(-6,0) ~ F,
                                       m3e2d == 1 ~ T)

```

1a. More relevant--- c(-6, 2) as FALSE rather than c(-6, 0)? 

In particular, based on codebook linked to and raw data table here, seems like 2 == no  -> false

![image](https://user-images.githubusercontent.com/21369316/99748136-eda84680-2aa9-11eb-8d25-17976817586d.png)

1b. Probably less relevant/more interpretive --- m3e2d or m3e2?

Probably just cleaning up the comment, since text emphasizes living with a new partner, but comment suggested something more like m3e2 (Currently involved in a relationship with someone other than father?) and less like m3e2d (Do you and current partner live together most of the time?)

What code changes do: i left as m3e2d (living with partner) but changed the %in% part to be c(-6, 2) so that 2 is  false rather than na

![image](https://user-images.githubusercontent.com/21369316/99748455-8fc82e80-2aaa-11eb-8a5b-5f535c21ab2e.png)

2. Order of imputation and scale construction

I got the same missingness matrix as your output, so I think both the original code and the new rowsums-based scale code result in the same thing of a derived scale being missing if any of the sub-items are missing

For at least some of the scales i think this leads to diff results than an approach that (1) imputes all scale sub-items, (2) constructs scale on basis of both observed and imputed, e.g., while the majority of those missing any of the impulsiveness scale items are missing all 6 items, there are some (this is pre-analytic sample filtering) who have some but not all sub-items missing

![image](https://user-images.githubusercontent.com/21369316/99748797-314f8000-2aab-11eb-9dfb-69f45336817e.png)

I don't think we should change approach, esp since scales aren't the main focus, but tried to be more explicit about this in the comments

**Note**: not a question but a note is that i wanted to make sure `code_agg_scales` returned same things as earlier code version, so constructed with both older and newer code and confirmed identical, e.g.

![image](https://user-images.githubusercontent.com/21369316/99748933-8095b080-2aab-11eb-83a2-9f946606dddd.png)

![image](https://user-images.githubusercontent.com/21369316/99748948-89868200-2aab-11eb-843d-55cefeccb593.png)

**Comment by ilundberg** [comment]
1a. I agree. Thanks for this fix.

1b. We do want the one we currently have (m3e2d), which requires coresidence, because this matches how the mediator in wave 4 is defined (requiring coresidence). In the original paper, Wildeman et al. write "In addition, we include a dummy variable indicating a new romantic partner moved into the mother’s household." As you note, our text also says that, with the Wildeman example opening with this line: "We focus on one mediator from Wildeman et al. (2012): paternal incarceration may cause the mother to reside with a new partner, which could in turn affect her depression." So coresidence is necessary here, and we should keep m3e2d as you have done. I WILL UPDATE THE COMMENT

2. How to do imputation with scales is a fair point to bring up.

The way we do it---construct the scale, which is missing if you are missing any item, then impute---is correct here because I imagine it is how the original authors did it. It seems like the simplest thing to do.

The alternative that seems reasonable to me is to first impute the individual missing items, then aggregate to a scale on the imputed datasets. That seems potentially more correct, but also much more complex, so we're not thinking about that here since our goal is a faithful replication.

The alternative you propose in the comments---average over whatever scale items are observed for each person---seems like an approach I'd rather not suggest. Suppose you have a scale of eviction, hunger, and electricity shutoffs. If someone only reports eviction and hunger, then the average of those two items is not really the same construct as the average of the three items. So, averaging those two and calling it complete data seems like something we don't want to encourage. For this reason, I am deleting these comments:
```
#' Can change by setting na.rm = TRUE in rowsums and adjusting
#' the denominator on the scale to be person-specific
```

Thanks for writing and testing ``code_agg_scales``.

One more thing: you may have caught an error here but didn't realize it. In the shared parenting responsibility scale, you added this comment.

> Shared responsibility (reverse code from 1 = often; 4 = never; those who skip are often)

In the code, -6 gets coded as 4 (which is how we ultimately code "often") on variables like the screenshot below.
But I think I intended to code the -6 as "never" since the questions are skipped if there is no father.
I am updating to code the -6 as "never", in the code and in the comment.
This affects the construction of ``shared.responsibility.y3`` and ``cooperation.y3``.

I ran the updated code and updated the results in Overleaf.

I have merged your changes in [this commit](https://github.com/ilundberg/replication/commit/50d661d03ba0a3f55ff97cdae8a033eea193ab87).
Then, I merged my additional tweaks in [this commit](https://github.com/ilundberg/replication/commit/12e6656d0db970313804a4e9f615a32936d47232).

**Comment by rjohnsondc** [comment]
> 1a. I agree. Thanks for this fix.

Sounds good
> 
> 1b. We do want the one we currently have (m3e2d), which requires coresidence, because this matches how the mediator in wave 4 is defined (requiring coresidence). In the original paper, Wildeman et al. write "In addition, we include a dummy variable indicating a new romantic partner moved into the mother’s household." As you note, our text also says that, with the Wildeman example opening with this line: "We focus on one mediator from Wildeman et al. (2012): paternal incarceration may cause the mother to reside with a new partner, which could in turn affect her depression." So coresidence is necessary here, and we should keep m3e2d as you have done. I WILL UPDATE THE COMMENT
> 

Yes that makes sense --- I figured it was just a comment/variable disconnect and agree that coresidence (m3e2d) is defensible.

> 1. How to do imputation with scales is a fair point to bring up.
> 
> The way we do it---construct the scale, which is missing if you are missing any item, then impute---is correct here because I imagine it is how the original authors did it. It seems like the simplest thing to do.
> 
> The alternative that seems reasonable to me is to first impute the individual missing items, then aggregate to a scale on the imputed datasets. That seems potentially more correct, but also much more complex, so we're not thinking about that here since our goal is a faithful replication.
> 
> The alternative you propose in the comments---average over whatever scale items are observed for each person---seems like an approach I'd rather not suggest. Suppose you have a scale of eviction, hunger, and electricity shutoffs. If someone only reports eviction and hunger, then the average of those two items is not really the same construct as the average of the three items. So, averaging those two and calling it complete data seems like something we don't want to encourage. For this reason, I am deleting these comments:

> ```
> #' Can change by setting na.rm = TRUE in rowsums and adjusting
> #' the denominator on the scale to be person-specific
> ```
> 
> Thanks for writing and testing `code_agg_scales`.
> 

Yeah I should have been more precise about the two options: (1) imputing scale items and then averaging over full scale versus (2) listwise del with diff denominator. More meant that 1 is defensible and we should be clear that we didn't do.


> One more thing: you may have caught an error here but didn't realize it. In the shared parenting responsibility scale, you added this comment.
> 
> > Shared responsibility (reverse code from 1 = often; 4 = never; those who skip are often)
> 
> In the code, -6 gets coded as 4 (which is how we ultimately code "often") on variables like the screenshot below.
> But I think I intended to code the -6 as "never" since the questions are skipped if there is no father.
> I am updating to code the -6 as "never", in the code and in the comment.
> This affects the construction of `shared.responsibility.y3` and `cooperation.y3`.
> 
> I ran the updated code and updated the results in Overleaf.
> 
> I have merged your changes in [this commit](https://github.com/ilundberg/replication/commit/50d661d03ba0a3f55ff97cdae8a033eea193ab87).
> Then, I merged my additional tweaks in [this commit](https://github.com/ilundberg/replication/commit/12e6656d0db970313804a4e9f615a32936d47232).

Yes I did notice that and thought it was weird, but i thought i might be misreading things since i got confused with the scale reversals. I agree that -6 should be coded as never and hopefully easy to change via the passed-in function.

Thanks!
